[package]
name = "gorm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"gorm_macros"
]

[dependencies]
gorm_macros = { path = "gorm_macros" }
